### ISSUE TITLE
Waze Editor bug? (this.setLayerZIndex is not a function)

### ISSUE THREAD

**Issue by MarcHagen** [Glodenox/wme-image-overlays#14] opened 2019-11-20 22:53 UTC
```
vendor-93d30041d65a17892c34.js:1 Uncaught TypeError: this.setLayerZIndex is not a function
    at t.setLayerIndex (vendor-93d30041d65a17892c34.js:1)
    at HTMLImageElement.eval (userscript.html?id=919394a0-b527-4027-844c-2ad4bb8addeb:781)
```

And the "formatted" code from  vendor.js:
```
        setLayerIndex: function(e, t) {
            var n = this.getLayerIndex(e);
            if (t < 0 ? t = 0 : t > this.layers.length && (t = this.layers.length),
            n != t) {
                this.layers.splice(n, 1),
                this.layers.splice(t, 0, e);
                for (var r = 0, i = this.layers.length; r < i; r++)
                    this.setLayerZIndex(this.layers[r], r); << Broken
                this.events.triggerEvent("changelayer", {
                    layer: e,
                    property: "order"
                }),
                this.allOverlays && (0 === t ? this.setBaseLayer(e) : this.baseLayer !== this.layers[0] && this.setBaseLayer(this.layers[0]))
            }
        },
```

**Comment by Glodenox** [comment] 2019-11-21 07:37
Hey,
I'm aware of this issue. It is caused by [an update](https://www.waze.com/forum/viewtopic.php?f=819&t=294063) that Waze pushed way sooner than I had expected.

As a temporary workaround, you could install [this small userscript](https://greasyfork.org/scripts/391783-wme-fix-map-object) that counteracts the changes made by Waze. It will also help with all other userscripts.

**Comment by MarcHagen** [comment] 2019-11-21 09:39
> Hey,
> I'm aware of this issue. It is caused by [an update](https://www.waze.com/forum/viewtopic.php?f=819&t=294063) that Waze pushed way sooner than I had expected.
> 
> As a temporary workaround, you could install [this small userscript](https://greasyfork.org/scripts/391783-wme-fix-map-object) that counteracts the changes made by Waze. It will also help with all other userscripts.

Perfect, thanks for the temporary workaround.

**Comment by Glodenox** [comment] 2019-11-29 23:33
This issue has been fixed with the recent release :)

**Closed as completed by Glodenox** 2019-11-29 23:33 UTC
